name: flutter_dotted
description: This package allows you to draw dotted lines with Flutter. You can draw a beautiful dotted line around the container.
version: 0.0.4
homepage: https://github.com/arsarsars1/flutter_dotted.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

